### ISSUE TITLE
NPE on getLastFailedConnection since it do null.intValue()

### ISSUE THREAD

**Issue by dprevost-LMI** [launchdarkly/react-native-client-sdk#160] opened 2022-10-14 17:32 UTC
**Is this a support request?**
I guess not

**Describe the bug**
We are having some inconsistent issues where the allFlags return an empty object and to get more information, I tried to use the `getLastFailedConnection` to see if there is any failure. Still, I guess there is not since it is doing an NPE.

Since `getLastFailedConnection()` is null clearly the below will be a NPE....
```
promise.resolve(LDClient.getForMobileKey(environment).getConnectionInformation().getLastFailedConnection().intValue());
```

**To reproduce**
Call getLastFailedConnection without any failure you will get a NPE

**Expected behavior**
Return null as mentioned in the doc 

```
        /**
         * Returns the most recent successful flag cache update in millis from the epoch
         * or null if flags have never been retrieved.
         *
         * @param environment
         *   Optional string to execute the function in a different environment than the default.
         * @returns 
         *   A promise containing a number representing the status of the connection to LaunchDarkly, 
         *   or null if a successful connection has yet to be established.
         */
        getLastSuccessfulConnection(environment?: string): Promise<number | null>;
```

**Logs**
```
 Attempt to invoke virtual method 'int java.lang.Long.intValue()' on a null object reference
```

**SDK version**
The version of this SDK that you are using.

**Language version, developer tools**
React native

**OS/platform**
Mac

**Additional context**

**Comment by louis-launchdarkly** [comment] 2022-10-18 16:38
Hello @dprevost-LMI, thank you for reporting the issue you see.

Given the logs said `java`, can you confirm that the issue is happening for android? If you use iOS, do you see this issue also for iOS?

Filed internally as 173523.

**Comment by louis-launchdarkly** [comment] 2023-04-22 00:20
Closing this as we never heard back from the customer. If you encounter this issue in the latest 7.x build (https://github.com/launchdarkly/react-native-client-sdk/releases/tag/7.1.4), please feel free to open a new issue.

**Comment by louis-launchdarkly** [comment] 2023-04-22 00:23
I don't think that part of the code had changed so we will need to test this for 7.x and see what is the current state.

**Comment by dprevost-LMI** [comment] 2023-04-24 18:04
> Hello @dprevost-LMI, thank you for reporting the issue you see.
> 
> Given the logs said `java`, can you confirm that the issue is happening for android? If you use iOS, do you see this issue also for iOS?
> 
> Filed internally as 173523.

Yes, it was for Android. I did not test for iOS, but by code inspection, you can easily find that a null not checked can result in a NPE

**Comment by louis-launchdarkly** [comment] 2023-05-11 00:12
Hello @dprevost-LMI, do you mind letting me know which version of the SDK you are using? The Exception handling for that method is updated in the RN SDK 7.x - the behavior is now different. 

The Type doc is still not accurate though, in 7.x, when there is no failure for `getLastFailedConnection` (or success for `getLastSuccessfulConnection` in the document you quoted), it is returning a resolved promise with value 0 instead of `null`.

**Comment by dprevost-LMI** [comment] 2023-05-18 00:03
Hey!

As you can see in [this code](https://github.com/launchdarkly/android-client-sdk/blob/6f5fe8923354cfc89be87cb97845c11257825486/launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/ConnectivityManager.java#L303C1-L304), the lasatFailedConnnection can be set to null.

So it would be just natural to actually do a null check in [that code](https://github.com/launchdarkly/react-native-client-sdk/blob/d45a48786e33307dad440d4c0d0eada26f7901f0/android/src/main/java/com/launchdarkly/reactnative/LaunchdarklyReactNativeClientModule.java#L649)

So the fix would be:

```
const lastFailedConnection  = LDClient.getForMobileKey(environment).getConnectionInformation().getLastFailedConnection();
promise.resolve(lastFailedConnection == null ? null: lastFailedConnection.intValue() );
```

Or as you said, change the doc [there](https://github.com/launchdarkly/react-native-client-sdk/blob/d45a48786e33307dad440d4c0d0eada26f7901f0/index.d.ts#L695-L703)

**Comment by dprevost-LMI** [comment] 2023-06-07 16:40
@louis-launchdarkly you need more from me?

**Comment by louis-launchdarkly** [comment] 2023-06-09 23:53
Hello @dprevost-LMI, thank you for the reply - sorry that there is an issue about the workflow (which should have remove the `waiting for feedback` label). I will discuss with the JS engineer on what is the behavior the SDK should do.

**Comment by yusinto** [comment] 2023-06-12 15:55
@dprevost-LMI we are fixing the null error and will release a new version soon. Thank you for reporting this.

**Closed** 2023-06-22 21:05 UTC
