### ISSUE TITLE
Crashed when launch android app after install / add React Native SDK

### ISSUE THREAD

**Issue by pramahaditamaputra-ralali** [launchdarkly/react-native-client-sdk#94] opened 2021-09-22 04:53 UTC
**Is this a support request?**
No

**Describe the bug**
Crash when run android app, but its normal on iOS after install the SDK

**To reproduce**
i'm using react native version 0.64.2 then install the launch darkly react native SDK, then run the android one after that the app forced close directly but its not happen in iOS App.

**Expected behavior**
The android app should not crashed like the iOS app

**SDK version**
The lastest one 5.0.1

**Language version, developer tools**
Javascript, React Native

**OS/platform**
MacOS

**Additional context**

**Comment by bwoskow-ld** [comment] 2021-09-22 16:28
Hi @pramahaditamaputra-ralali ,

Although you indicated that this is not a support request, there's not yet enough information to say if your reported issue is because of a bug in the SDK or because of improper usage of some sort. We don't have enough information to reproduce or diagnose the problem. With this in mind my recommendation is to [file a support request](https://support.launchdarkly.com/hc/en-us/requests/new) where you can securely share code snippets, application logs, and so forth to further diagnose the issue. Our engineering team works closely with our support team and will contribute to the conversation as appropriate.

In the meantime I'm going to close this ticket so as to consolidate our communications over there.

Cheers,
@bwoskow-ld

**Closed by bwoskow-ld** 2021-09-22 16:28 UTC

**Comment by Knight704** [comment] 2021-12-14 06:22
I have similar issue, for me crash was related to the fact that apart from launchdarkly some other native android libs had dependency on okhttp, so that they had different version and incosistent, adding

```
implementation "com.squareup.okhttp3:okhttp:4.9.1"
implementation "com.squareup.okhttp3:logging-interceptor:4.9.1"
implementation "com.squareup.okhttp3:okhttp-urlconnection:4.9.1"
```

to the end of the dependency list in app/build.gradle fixed the problem
