### ISSUE TITLE
LDClient not initialised [Error: LDClient.getForMobileKey() was called before init()!]

### ISSUE THREAD

**Issue by vkundapur** [launchdarkly/react-native-client-sdk#186] opened 2023-02-27 06:42 UTC
**Describe the bug**
On launch of the app, I am getting the following exception while trying to initialise the SDK in **Android**.
` Launch Darkly LDClient not initialised [Error: LDClient.getForMobileKey() was called before init()!]`

**To reproduce**
Here is the code that are running to initialise the SDK:
```
// LaunchDarkly/index.ts
// Launch Darkly Singleton client
export default class LaunchDarkly {
  static client: LDClient | null = null

  static async initialiseLDClient(user: LDUser) {
    if (!LaunchDarkly.client) {
      console.log('Launch Darkly', 'creating new LDClient')
      LaunchDarkly.client = new LDClient()
    }
    const ldConfig: LDConfig = { mobileKey: Config.LAUNCH_DARKLY_SDK_KEY }
    try {
      const isInitialised = await LaunchDarkly.client.isInitialized()
      if (isInitialised) {
        console.log('Launch Darkly', 'LDClient already initialised')
        return
      }
    } catch (err) {
      console.log('Launch Darkly', 'LDClient not initialised', err)
    } finally {
      await LaunchDarkly.client.configure(ldConfig, user)
    }
  }
}
```

Initialisation of the client is done in the code below:
```
  useEffect(() => {
    LaunchDarkly.initialiseLDClient({ key: ANONYMOUS_USER_ID, anonymous: true })
      .then(() => {
        console.log('Launch Darkly', 'Launch Darkly initialised successfully')
      })
      .catch(err => {
        console.log('Launch Darkly', 'Launch Darkly initialisation failed', err)
        trackError(
          'Launch Darkly initialisation failed',
          {},
          ErrorSource.CUSTOM,
          err,
        )
      })
  }, [trackError])
```

The SDK returns an exception during initialisation but then automatically recovers in the next run as you can see from the logs. 

**Expected behaviour**
There should be no exception thrown.

**Logs**
'Launch Darkly', 'LDClient not initialised', [Error: SDK has not been configured]
'Launch Darkly', 'Launch Darkly initialised successfully'

**SDK version**
"launchdarkly-react-native-client-sdk": "^6.3.0",

**OS/platform**
Android OS v13.0
"react-native": "0.70.5",

**Comment by louis-launchdarkly** [comment] 2023-03-02 00:08
Hello @vkundapur, thank you for reaching out about this issue. I will need to discuss this with the engineer on the team who is more familiar with React lifecycle - this seems like the client was accessed too soon (before the initialization). 

In the meantime, given you are using React Native 0.70, we also recommend you migrated to use the 7.x version of the LaunchDarkly React Native SDK, as that has more stability fixes in addition to the support of Contexts.

Filed Internally as 190729.

**Comment by louis-launchdarkly** [comment] 2023-03-16 22:53
Hello @vkundapur, can you try the code with the latest version of the SDK [7.1.2](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/7.1.2) and see is this still an issue that is happening? We recently released more fixes, and I want to know was that resolved the issue, or if this is still something we need to look into more.

**Comment by vkundapur** [comment] 2023-03-17 06:30
Thanks @louis-launchdarkly. I'll check and get back to you on this.

**Comment by vkundapur** [comment] 2023-03-17 07:12
@louis-launchdarkly I am still getting the same error after updating to SDK 7.1.2.

**Comment by vkundapur** [comment] 2023-03-31 06:32
@louis-launchdarkly Any update on this? Let me know if you need any additional information.

**Comment by Soft-Gurus** [comment] 2023-04-20 05:56
[Same issue in 7.1.x with RN 0.71.6 in android only](https://github.com/launchdarkly/react-native-client-sdk/issues/79#issuecomment-1515728619)

**Comment by louis-launchdarkly** [comment] 2023-04-26 23:47
Hello @vkundapur, 

Looking at your code, is there a reason you called LaunchDarkly.client.isInitialized() before calling aunchDarkly.client.configure(ldConfig, user)? Looking at https://github.com/launchdarkly/react-native-client-sdk/blob/main/index.d.ts#L610-L620 - `isInitialized()` is checking does the SDK has a mobile key and is ready to serve flags, but your configure call is in the `finally` portion of the code, so the client is not initialized the first time you check it.

**Comment by vkundapur** [comment] 2023-04-27 10:34
@louis-launchdarkly The intent is to see if SDK is already initialise and not call the `LaunchDarkly.client.configure` method if it is already initialised.

**Comment by louis-launchdarkly** [comment] 2023-04-27 16:56
Look at the test app we provided with the SDK https://github.com/launchdarkly/react-native-client-sdk/blob/main/ManualTestApp/App.tsx#L67

I think when you see the client does not exist, you want to do a configure call there:
```
    const ldConfig: LDConfig = { mobileKey: Config.LAUNCH_DARKLY_SDK_KEY }
    if (!LaunchDarkly.client) {
      // If we get to this line, the client does not exist and won't be initialized yet so it is safe to call configure once
      console.log('Launch Darkly', 'creating new LDClient')
      LaunchDarkly.client = new LDClient()
      await LaunchDarkly.client.configure(ldConfig, user)
    }
```

**Comment by louis-launchdarkly** [comment] 2023-04-27 17:00
Hello @mikevercoelen and @Soft-Gurus, as I mentioned in the message above, we have a ManualTestApp that demos the init process https://github.com/launchdarkly/react-native-client-sdk/blob/main/ManualTestApp/App.tsx#L30 and I was not able to reproduce the issue using that code, so I would recommend trying to model your init like the test app accordingly. Or if you can provide your code, either on this issue (or if you want privacy, via a [Support ticket](https://support.launchdarkly.com/hc/en-us)), we can try to see what's wrong in your case.

**Comment by louis-launchdarkly** [comment] 2023-05-09 22:30
Closing as there is no further feedback/comment.

**Closed by louis-launchdarkly** 2023-05-09 22:30 UTC
